# Generated by Django 6.0.4 on 2026-04-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('EBOOK', 'E-Book'), ('PODCAST', 'Podcast'), ('GUIDE', 'Guide Pratique')], max_length=20)),
                ('description', models.TextField()),
                ('file_url', models.URLField(blank=True, help_text='Lien vers S3 ou Cloudinary', null=True)),
                ('audio_url', models.URLField(blank=True, help_text='Lien streaming podcast', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix en FCFA, 0 si gratuit', max_digits=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
            ],
        ),
    ]
